language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
    - php: 7.4
      env: WEBSITE=true

sudo: false

env:
  global:
    - WEBSITE=false
    - CC_TEST_REPORTER_ID=298bdec6344bc69dfae3daf835a94e21c1dc3b00bfe7fae7cdaa3575b1bfea3e

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = 'nightly' ]]; then composer update --ignore-platform-reqs; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'nightly' ]]; then composer update; fi;

script:
  - if [[ $WEBSITE = 'true' ]]; then php bin/easy-doc build --verbose; fi
  - if [[ $WEBSITE != 'true' ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml; fi

after_script:
  - cp coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/website
    on:
      branch: master
      condition: $WEBSITE = 'true'
